# Generated by Django 5.1.5 on 2025-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
